### ISSUE TITLE
NuGet Package broken 'SixLabors.ImageSharp (>= 1.0.0-beta0002)' missing

### ISSUE THREAD

**Issue by atomroflman** [Sergio0694/NeuralNetwork.NET#81]
While installing the Nuget package there is a package reference error.
I expect the package isn't online anymore. 

Package Source is Nuget.org.

**Comment by Sergio0694** [comment]
Hey @atomroflman - that's weird, the package should be online and available, see [here](https://www.nuget.org/packages/SixLabors.ImageSharp/).

Which framework are you using? I've had other users reporting issues on .NET Framework, as older versions of that don't properly support .NET Standard 2.0.
If that's your case, could you make sure you're on at least .NET Framework 4.7.1 and try again?

**Comment by atomroflman** [comment]
Hey @Sergio0694 - indeed it is weird. I already found the reference you linked, too. 
I had my project pointing on 4.6.2 first, but changing to 4.7.1 made no difference. 
The error remains.

**Comment by Sergio0694** [comment]
Mh, I think it's more of a .NET Standard or NuGet issue than an issue with this library specifically.

Now that I think about it, what kind of .csproj file are you using for your project? It should work fine if you're using the new .csproj format ([see here](http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/)), which you can also see in the Cuda sample project in the repo.
If you were using the old .csprof format, would you mind upgrading to the new one following the link above, and let me know if that solves the issue for you? Thanks! 😄

**Comment by atomroflman** [comment]
Okay got it. Creating a new project with VS2017 and adding the files did the job.
The issue was the project file was created within VS2015.
Thanks a lot. 👍

**Comment by Sergio0694** [comment]
@atomroflman Awesome, glad to hear the issue has been resolved.
I hope you'll enjoy using this library! 😊
