### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by bayramakgul** [Sergio0694/NeuralNetwork.NET#87]
Hello, I accomplish to train the network by my own dataset,
but I dont know, how can I predict or classify (or **sim**ulate or whatever the name) any input data.

for example in matlap:
**y=sim(net, x);**

Thank you.

**Comment by Sergio0694** [comment]
Hi, thank you for using the library 😄
Doing inference with a trained network is pretty straightforward: one you have your `INeuralNetwork` instance, you'll see there are two `Forward` methods available.

- The first overload takes a `float[]` and returns a `float[]`, so it only does inference on a single sample **X** (with _n_ features), and returns an output sample **Y** with _m_ features (depending on the last layer of the network).
- The second one does the same, but processes multiple samples in parallel, and returns a `float[,]` object, where each row is a sample, with _m_ features.

Let me know if this works for you!

**Comment by bayramakgul** [comment]
Thank you, that was exactly the answer I wanted.  :)
