### ISSUE TITLE
Thread-safe?

### ISSUE THREAD

**Issue by neil-119** [Sergio0694/NeuralNetwork.NET#91]
Awesome library! I wanted to ask if the library is thread-safe? We've been wanting to use it in an ASP.NET application to train (very small) NNs on the fly.

**Comment by Sergio0694** [comment]
Hey, thank you for your feedback, glad you like the library!
Yes, if you run the training on the CPU it should be thread safe, though keep in mind that all CPU operations use `Parallel.For` behind the scenes, so if you spawn too many instances on your ASP.NET services you may have issues with too many parallel tasks running at once.
Let me know how it goes! 😄

**Comment by neil-119** [comment]
Awesome, will do 👍 Still a few weeks before I have to tackle this task, but looks like I found exactly what I needed. Thanks!
